import type { APIRoute } from 'astro';

// Dynamic robots.txt: allows all crawlers and points to the sitemap index
// generated by @astrojs/sitemap, using the configured site origin.
export const GET: APIRoute = ({ site }) => {
  const sitemapUrl = site ? new URL('sitemap-index.xml', site).href : '/sitemap-index.xml';
  const body = `User-agent: *
Allow: /

Sitemap: ${sitemapUrl}
`;

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
